backend:
  name: github
  repo: PhDoanh/content
  branch: main
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "media"
public_folder: "/media"

site_url: https://phdoanh.github.io/blog
display_url: https://phdoanh.github.io/blog
logo_url: https://phdoanh.github.io/blog/static/icon.png

collections:
  - name: "ai-orchestration"
    label: "AI Orchestration"
    label_singular: "AI Article"
    folder: "ai-orchestration"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} - {{description}}"
    sortable_fields:
      fields: ['title', 'date', 'commit_date']
      default:
        field: date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", default: "vi", required: false }
      - { name: "draft", widget: "hidden", default: true, required: false }
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "best-practices"
    label: "Best Practices"
    label_singular: "Best Practice"
    folder: "best-practices"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} - {{date | date('DD/MM/YYYY')}}"
    sortable_fields:
      fields: ['title', 'date', 'commit_date']
      default:
        field: date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", default: "vi", required: false}
      - { name: "draft", widget: "hidden", default: true, required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "system-foundations"
    label: "System Foundations"
    label_singular: "System Foundation"
    folder: "system-foundations"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} - {{date | date('DD/MM/YYYY')}}"
    sortable_fields:
      fields: ['title', 'date', 'commit_date']
      default:
        field: date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", default: "vi", required: false}
      - { name: "draft", widget: "hidden", default: true, required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "beyond-code"
    label: "Beyond Code"
    label_singular: "Beyond Code"
    folder: "beyond-code"
    create: false
    publish: false
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    editor:
      preview: true
    summary: "{{title}} - {{date | date('DD/MM/YYYY')}}"
    sortable_fields:
      fields: ['title', 'date', 'commit_date']
      default:
        field: date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", required: false}
      - { name: "draft", widget: "hidden", required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "tags"
    create: false
    publish: false
    delete: false
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", required: false}
      - { name: "draft", widget: "hidden", required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "root-articles"
    label: "Root Articles"
    label_singular: "Root Article"
    folder: "."
    create: false
    publish: false
    delete: false
    filter:
      field: path
      pattern: "^[^/]+$"
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", required: false}
      - { name: "draft", widget: "hidden", required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
