backend:
  name: github
  repo: PhDoanh/content
  base_url: https://cms-proxy.pgdoanh711.workers.dev
  branch: main
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "media"
public_folder: "/media"

site_url: https://phdoanh.github.io/blog
display_url: https://phdoanh.github.io/blog
logo_url: https://phdoanh.github.io/blog/static/icon.png

collections:
  - name: "ai-orchestration"
    label: "AI Orchestration"
    label_singular: "AI Article"
    folder: "ai-orchestration"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
    filter:
      pattern: '^(?!index\.md$)(.*\.md)$' 
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} ðŸŒ± Updated on {{updated}} ðŸŒ± {{description | truncate(50, '...')}}"
    sortable_fields:
      fields: ['updated', 'title', 'commit_author']
      default:
        field: updated
        direction: Descending
    # view_filters:
    #   default: drafts
    #   filters:
    #     - name: drafts
    #       label: Drafts
    #       field: draft
    #       pattern: true
    #     - name: in-review
    #       label: "In Review"
    #       field: pending_review
    #       pattern: true
    view_groups:
      default: by-language
      groups:
        - name: by-language
          label: Language
          field: lang
        - name: by-year
          label: "Year"
          field: updated
          pattern: "^(\\d{4})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", default: "", required: false}
      - name: "lang"
        label: "Language"
        widget: "select"
        options:
          - label: "Tiáº¿ng Viá»‡t"
            value: "vi"
          - label: "English"
            value: "en"
          - label: "æ—¥æœ¬èªž"
            value: "ja"
        required: false
      - { name: "publish", widget: "hidden", default: true, required: false }
      - { label: "Updated on", name: "updated", widget: "datetime", date_format: "dd/MM/yyyy", time_format: false, format: 'yyyy-MM-dd', required: false }
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, tags separated by commas, .e.g. the-1st-tag, 2nd-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", default: [], required: false}
      - { name: "cssclasses", widget: "hidden", default: [], required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "image", default: "", choose_url: true, required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "best-practices"
    label: "Best Practices"
    label_singular: "Best Practice"
    folder: "best-practices"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
    filter:
      pattern: '^(?!index\.md$)(.*\.md)$' 
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} ðŸŒ± Updated on {{updated}} ðŸŒ± {{description | truncate(50, '...')}}"
    sortable_fields:
      fields: ['updated', 'title', 'commit_author']
      default:
        field: updated
        direction: Descending
    # view_filters:
    #   default: drafts
    #   filters:
    #     - name: drafts
    #       label: Drafts
    #       field: draft
    #       pattern: true
    view_groups:
      default: by-language
      groups:
        - name: by-language
          label: Language
          field: lang
        - name: by-year
          label: "Year"
          field: updated
          pattern: "^(\\d{4})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", default: "", required: false}
      - name: "lang"
        label: "Language"
        widget: "select"
        options:
          - label: "Tiáº¿ng Viá»‡t"
            value: "vi"
          - label: "English"
            value: "en"
          - label: "æ—¥æœ¬èªž"
            value: "ja"
        required: false
      - { name: "publish", widget: "hidden", default: true, required: false}
      - { label: "Updated on", name: "updated", widget: "datetime", date_format: "dd/MM/yyyy", time_format: false, format: 'yyyy-MM-dd', required: false }
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, tags separated by commas, .e.g. the-1st-tag, 2nd-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", default: [], required: false}
      - { name: "cssclasses", widget: "hidden", default: [], required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "image", default: "", choose_url: true, required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "system-foundations"
    label: "System Foundations"
    label_singular: "System Foundation"
    folder: "system-foundations"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
    filter:
      pattern: '^(?!index\.md$)(.*\.md)$' 
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}} ðŸŒ± Updated on {{updated}} ðŸŒ± {{description | truncate(50, '...')}}"
    sortable_fields:
      fields: ['updated', 'title', 'commit_author']
      default:
        field: updated
        direction: Descending
    # view_filters:
    #   default: drafts
    #   filters:
    #     - name: drafts
    #       label: Drafts
    #       field: draft
    #       pattern: true
    view_groups:
      default: by-language
      groups:
        - name: by-language
          label: Language
          field: lang
        - name: by-year
          label: "Year"
          field: updated
          pattern: "^(\\d{4})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", default: "", required: false}
      - name: "lang"
        label: "Language"
        widget: "select"
        options:
          - label: "Tiáº¿ng Viá»‡t"
            value: "vi"
          - label: "English"
            value: "en"
          - label: "æ—¥æœ¬èªž"
            value: "ja"
        required: false
      - { name: "publish", widget: "hidden", default: true, required: false}
      - { label: "Updated on", name: "updated", widget: "datetime", date_format: "dd/MM/yyyy", time_format: false, format: 'yyyy-MM-dd', required: false }
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, tags separated by commas, .e.g. the-1st-tag, 2nd-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", default: [], required: false}
      - { name: "cssclasses", widget: "hidden", default: [], required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "image", default: "", choose_url: true, required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  # - name: "beyond-code"
  #   label: "Beyond Code"
  #   folder: "beyond-code"
  #   create: false
  #   publish: false
  #   delete: false
  #   nested:
  #     depth: 100
  #   filter:
  #     pattern: '^(?!index\.md$)(.*\.md)$' 
  #   extension: md
  #   format: frontmatter
  #   slug: "{{slug}}"
  #   summary: "{{title}} ðŸŒ± Updated on {{commit_date | truncate(10, ' ')}} ðŸŒ± {{description | truncate(50, '...')}}"
  #   sortable_fields:
  #     fields: ['commit_date', 'title', 'commit_author']
  #     default:
  #       field: commit_date
  #       direction: Descending
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Description", name: "description", widget: "text", required: false }
  #     - { name: "permalink", widget: "hidden", required: false}
  #     - { name: "lang", widget: "hidden", required: false}
  #     - { name: "publish", widget: "hidden", required: false}
  #     - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, tags separated by commas, .e.g. the-1st-tag, 2nd-tag", required: false, allow_add: true }
  #     - { name: "aliases", widget: "hidden", required: false}
  #     - { name: "cssclasses", widget: "hidden", required: false}
  #     - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
  #     - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
  #     - { label: "Content", name: "body", widget: "markdown" }

  # - name: "tags-page"
  #   label: "Tags Page"
  #   folder: "tags"
  #   create: false
  #   publish: false
  #   delete: false
  #   extension: md
  #   format: frontmatter
  #   slug: "{{slug}}"
  #   summary: "{{title}} ðŸŒ± Updated on {{commit_date | truncate(10, ' ')}} ðŸŒ± {{description | truncate(50, '...')}}"
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Description", name: "description", widget: "text", required: false }
  #     - { name: "permalink", widget: "hidden", required: false}
  #     - { name: "lang", widget: "hidden", required: false}
  #     - { name: "publish", widget: "hidden", required: false}
  #     - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, tags separated by commas, .e.g. the-1st-tag, 2nd-tag", required: false, allow_add: true }
  #     - { name: "aliases", widget: "hidden", required: false}
  #     - { name: "cssclasses", widget: "hidden", required: false}
  #     - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
  #     - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
  #     - { label: "Content", name: "body", widget: "markdown" }

  # - name: "main-pages"
  #   label: "Main Pages"
  #   create: false
  #   publish: false
  #   delete: false
  #   extension: md
  #   format: frontmatter
  #   files:
  #     - name: "home"
  #       label: "Home Page"
  #       file: "/index.md"
  #       fields: 
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Description", name: "description", widget: "text", required: false }
  #         - { name: "permalink", widget: "hidden", required: false}
  #         - { name: "lang", widget: "hidden", required: false}
  #         - { name: "publish", widget: "hidden", required: false}
  #         - { name: "aliases", widget: "hidden", required: false}
  #         - { name: "cssclasses", widget: "hidden", required: false}
  #         - { name: "socialImage", widget: "hidden", required: false }
  #         - { label: "Content", name: "body", widget: "markdown" }
      
  #     - name: "contribution"
  #       label: "Contribution Page"
  #       file: "/contribution.md"
  #       fields: 
  #         - { label: "Title", name: "title", widget: "string" }
  #         - { label: "Description", name: "description", widget: "text", required: false }
  #         - { name: "permalink", widget: "hidden", required: false}
  #         - { name: "lang", widget: "hidden", required: false}
  #         - { name: "publish", widget: "hidden", required: false}
  #         - { name: "tags", widget: "hidden", required: false }
  #         - { name: "aliases", widget: "hidden", required: false}
  #         - { name: "cssclasses", widget: "hidden", required: false}
  #         - { name: "socialImage", widget: "hidden", required: false }
  #         - { label: "Content", name: "body", widget: "markdown" }
