backend:
  name: github
  repo: PhDoanh/content
  branch: main
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "media"
public_folder: "/media"

site_url: https://phdoanh.github.io/blog
display_url: https://phdoanh.github.io/blog
logo_url: https://phdoanh.github.io/blog/static/icon.png

collections:
  - name: "ai-orchestration"
    label: "AI Orchestration"
    label_singular: "AI Article"
    folder: "ai-orchestration"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
      path: { widget: string, label: 'Path' ,index_file: 'index' }
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}}"
    sortable_fields:
      fields: ['commit_date', 'title', 'commit_author']
      default:
        field: commit_date
        direction: Descending
    view_filters:
      default: drafts
      filters:
        - name: alice-and-bob
          label: "Alice's and Bob's Posts"
          field: author
          pattern: 'Alice|Bob'
        - name: posts-2020
          label: 'Posts published in 2020'
          field: date
          pattern: '2020'
        - name: drafts
          label: Drafts
          field: draft
          pattern: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", default: "vi", required: false }
      - { name: "draft", widget: "hidden", default: false, required: false }
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "best-practices"
    label: "Best Practices"
    label_singular: "Best Practice"
    folder: "best-practices"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
      path: { widget: string, label: 'Path', index_file: 'index' }
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}}"
    sortable_fields:
      fields: ['commit_date', 'title', 'commit_author']
      default:
        field: commit_date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", default: "vi", required: false}
      - { name: "draft", widget: "hidden", default: false, required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "system-foundations"
    label: "System Foundations"
    label_singular: "System Foundation"
    folder: "system-foundations"
    create: true
    publish: true
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
      path: { widget: string, label: 'Path', index_file: 'index' }
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}}"
    sortable_fields:
      fields: ['commit_date', 'title', 'commit_author']
      default:
        field: commit_date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", default: "vi", required: false}
      - { name: "draft", widget: "hidden", default: false, required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "beyond-code"
    label: "Beyond Code"
    folder: "beyond-code"
    create: false
    publish: false
    delete: false
    nested:
      depth: 100
      summary: "{{title}}"
      path: { widget: string, label: 'Path', index_file: 'index' }
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    editor:
      preview: true
    summary: "{{title}}"
    sortable_fields:
      fields: ['commit_date', 'title', 'commit_author']
      default:
        field: commit_date
        direction: Descending
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", required: false}
      - { name: "draft", widget: "hidden", required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "tags"
    label: "Tags"
    folder: "tags"
    create: false
    publish: false
    delete: false
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { name: "permalink", widget: "hidden", required: false}
      - { name: "lang", widget: "hidden", required: false}
      - { name: "draft", widget: "hidden", required: false}
      - { label: "Tags", name: "tags", widget: "list", hint: "Using kebab-case for tag name, e.g. the-example-tag", required: false, allow_add: true }
      - { name: "aliases", widget: "hidden", required: false}
      - { name: "cssclasses", widget: "hidden", required: false}
      - { label: "Social Description", name: "socialDescription", widget: "text", hint: "Description to be used for preview on social media", required: false }
      - { label: "Social Image", name: "socialImage", widget: "string", hint: "Link to preview image on social media", required: false }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    create: false
    publish: false
    delete: false
    extension: md
    format: frontmatter
    files:
      - name: "home"
        label: "Home Page"
        file: "/index.md"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { name: "permalink", widget: "hidden", required: false}
          - { name: "lang", widget: "hidden", required: false}
          - { name: "aliases", widget: "hidden", required: false}
          - { name: "cssclasses", widget: "hidden", required: false}
          - { name: "socialImage", widget: "hidden", required: false }
          - { label: "Content", name: "body", widget: "markdown" }
      
      - name: "contribution"
        label: "Contribution Page"
        file: "/contribution.md"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { name: "permalink", widget: "hidden", required: false}
          - { name: "lang", widget: "hidden", required: false}
          - { name: "draft", widget: "hidden", required: false}
          - { name: "tags", widget: "hidden", required: false }
          - { name: "aliases", widget: "hidden", required: false}
          - { name: "cssclasses", widget: "hidden", required: false}
          - { name: "socialImage", widget: "hidden", required: false }
          - { label: "Content", name: "body", widget: "markdown" }
